#!/usr/bin/env python3
"""Add a plain-English 'help' string to every key in maccs_keys.json.

MACCS legends use a shorthand (A = any atom, Q = heteroatom [not C/H],
X = halogen, QH = H-bearing heteroatom, nMring = n-membered ring). This maps
each of the 166 keys to a simple human-readable explanation for the UI tooltip.
"""

import json
from pathlib import Path

HELP = {
    1: "Contains an isotopically labelled atom",
    2: "Contains a very heavy element (atomic number > 103)",
    3: "Contains a heavier group 14–16 element (Ge, As, Se, Sn, Sb, Te, Pb…)",
    4: "Contains an actinide element",
    5: "Contains a group 3/4 transition metal (Sc, Ti, Y, Zr, Hf)",
    6: "Contains a lanthanide element",
    7: "Contains a group 5–7 transition metal (V, Cr, Mn, Mo…)",
    8: "A 4-membered ring containing a heteroatom",
    9: "Contains an iron-/platinum-group metal (Fe, Co, Ni, Pd, Pt…)",
    10: "Contains an alkaline-earth metal (Mg, Ca…)",
    11: "Contains a 4-membered ring",
    12: "Contains a coinage/group-12 metal (Cu, Zn, Ag, Cd, Au, Hg)",
    13: "An oxygen on a nitrogen bearing two carbons (N-oxide/hydroxylamine type)",
    14: "A disulfide (sulfur–sulfur single bond)",
    15: "A carbon bonded to three oxygens (carbonate/orthoester type)",
    16: "A 3-membered ring containing a heteroatom",
    17: "A carbon–carbon triple bond (alkyne)",
    18: "Contains a group 13 element (B, Al, Ga, In, Tl)",
    19: "Contains a 7-membered ring",
    20: "Contains silicon",
    21: "A C=C double bond where one carbon carries two heteroatoms",
    22: "Contains a 3-membered ring",
    23: "A carbon bonded to a nitrogen and two oxygens (carbamate type)",
    24: "A nitrogen–oxygen single bond",
    25: "A carbon bonded to three nitrogens (guanidine type)",
    26: "A C=C double bond inside a ring",
    27: "Contains iodine",
    28: "A CH2 group flanked by two heteroatoms",
    29: "Contains phosphorus",
    30: "A heteroatom bonded to three carbons and one more atom",
    31: "A heteroatom bonded to a halogen",
    32: "A carbon–sulfur–nitrogen chain",
    33: "A nitrogen–sulfur bond (sulfenamide type)",
    34: "A terminal =CH2 (methylene) double bond",
    35: "Contains an alkali metal (Li, Na, K…)",
    36: "A sulfur atom in a ring",
    37: "A carbon bonded to two nitrogens and an oxygen (urea type)",
    38: "A carbon bonded to two nitrogens and a carbon (amidine type)",
    39: "A sulfur bonded to three oxygens (sulfonate type)",
    40: "A sulfur–oxygen single bond",
    41: "A carbon–nitrogen triple bond (nitrile)",
    42: "Contains fluorine",
    43: "Two H-bearing heteroatoms separated by one atom",
    44: "Contains an uncommon element (not H,C,N,O,F,Si,P,S,Cl,Br,I)",
    45: "A nitrogen attached to a C=C double bond (enamine type)",
    46: "Contains bromine",
    47: "A sulfur and nitrogen separated by one atom",
    48: "A heteroatom bonded to three oxygens",
    49: "Contains a formally charged atom",
    50: "A C=C double bond with two carbon substituents",
    51: "A carbon–sulfur–oxygen chain",
    52: "A nitrogen–nitrogen bond",
    53: "Two H-bearing heteroatoms separated by three atoms",
    54: "Two H-bearing heteroatoms separated by two atoms",
    55: "An O–S–O linkage (sulfone/sulfonyl type)",
    56: "A nitrogen bearing two oxygens and a carbon (nitro/N-oxide type)",
    57: "An oxygen atom in a ring",
    58: "A sulfur flanked by two heteroatoms",
    59: "A sulfur attached to an aromatic ring by a non-aromatic bond",
    60: "A sulfur=oxygen double bond",
    61: "A sulfur bonded to three atoms",
    62: "A ring–bridge–ring junction (two rings joined by a non-ring bond)",
    63: "A nitrogen=oxygen double bond",
    64: "A sulfur attached to a ring by a non-ring bond",
    65: "An aromatic carbon–nitrogen bond (e.g. pyridine)",
    66: "A carbon bonded to three carbons and one more atom",
    67: "A heteroatom bonded to sulfur",
    68: "Two adjacent H-bearing heteroatoms",
    69: "A heteroatom bonded to an H-bearing heteroatom",
    70: "A nitrogen flanked by two heteroatoms",
    71: "A nitrogen–oxygen bond",
    72: "Two oxygens separated by two atoms",
    73: "A sulfur double-bonded to any atom",
    74: "Two methyl groups separated by one atom",
    75: "A ring nitrogen attached to an outside atom by a non-ring bond",
    76: "A C=C double bond with two substituents",
    77: "Two nitrogens separated by one atom",
    78: "A carbon=nitrogen double bond (imine type)",
    79: "Two nitrogens separated by two atoms",
    80: "Two nitrogens separated by three atoms",
    81: "A sulfur next to a branching atom",
    82: "A CH2 group next to an H-bearing heteroatom",
    83: "A 5-membered ring containing a heteroatom",
    84: "A primary amine (–NH2)",
    85: "A nitrogen bonded to three carbons (tertiary amine)",
    86: "A heteroatom flanked by two CH2/CH3 groups",
    87: "A halogen attached to a ring by a non-ring bond",
    88: "Contains sulfur",
    89: "Two oxygens separated by three atoms",
    90: "An H-bearing heteroatom four atoms from a CH2 group",
    91: "An H-bearing heteroatom five atoms from a CH2 group",
    92: "A carbon bonded to an oxygen, a nitrogen and a carbon",
    93: "A methyl group on a heteroatom (e.g. N-CH3, O-CH3)",
    94: "A heteroatom bonded to nitrogen",
    95: "A nitrogen and oxygen separated by two atoms",
    96: "Contains a 5-membered ring",
    97: "A nitrogen and oxygen separated by three atoms",
    98: "A 6-membered ring containing a heteroatom",
    99: "A carbon–carbon double bond (alkene)",
    100: "A CH2 group bonded to a nitrogen",
    101: "Contains a large ring (7 or more atoms)",
    102: "A heteroatom bonded to oxygen",
    103: "Contains chlorine",
    104: "An H-bearing heteroatom near a CH2 group",
    105: "A ring-fusion point (a ring atom with three ring connections)",
    106: "An atom bonded to three heteroatoms",
    107: "A halogen near a branching atom",
    108: "A methyl and a CH2 group separated by three atoms",
    109: "A CH2 group bonded to an oxygen",
    110: "A nitrogen–carbon–oxygen chain (amide/carbamate type)",
    111: "A nitrogen near a CH2 group",
    112: "A central atom with four connections",
    113: "An oxygen attached to an aromatic ring by a non-aromatic bond",
    114: "An ethyl group (CH3–CH2–)",
    115: "A methyl and CH2 separated by one atom",
    116: "A methyl and CH2 separated by two atoms",
    117: "A nitrogen and oxygen separated by one atom",
    118: "More than one –CH2–CH2– unit",
    119: "A nitrogen double-bonded to any atom",
    120: "More than one non-carbon atom in rings",
    121: "A nitrogen atom in a ring",
    122: "A nitrogen bonded to three atoms",
    123: "An O–C–O linkage (acetal/ester type)",
    124: "Two adjacent heteroatoms",
    125: "More than one aromatic ring",
    126: "An oxygen bridging two atoms by non-ring bonds (ether type)",
    127: "A ring atom bearing an oxygen outside the ring",
    128: "Two CH2 groups separated by three atoms",
    129: "Two CH2 groups separated by two atoms",
    130: "More than one pair of adjacent heteroatoms",
    131: "More than one H-bearing heteroatom",
    132: "An oxygen near a CH2 group",
    133: "A ring atom bearing a nitrogen outside the ring",
    134: "Contains a halogen (F, Cl, Br, I)",
    135: "A nitrogen attached to an aromatic ring by a non-aromatic bond",
    136: "More than one double-bonded oxygen (e.g. two carbonyls)",
    137: "A non-carbon atom in a ring (heterocycle)",
    138: "More than one heteroatom–CH2 unit",
    139: "A hydroxyl group (–OH)",
    140: "More than three oxygen atoms",
    141: "More than two methyl groups",
    142: "More than one nitrogen atom",
    143: "A ring atom bearing an oxygen outside the ring",
    144: "A non-aromatic chain attached across an aromatic ring",
    145: "More than one 6-membered ring",
    146: "More than two oxygen atoms",
    147: "A –CH2–CH2– unit (ethylene bridge)",
    148: "A heteroatom bonded to three atoms",
    149: "More than one methyl group",
    150: "A chain–ring–chain arrangement",
    151: "An N–H group (amine/amide hydrogen)",
    152: "An oxygen on a carbon bearing two carbons (secondary alcohol/ether)",
    153: "A heteroatom bonded to a CH2 group",
    154: "A carbonyl (C=O double bond)",
    155: "A CH2 group linking two atoms by non-ring bonds",
    156: "A nitrogen near a branching atom",
    157: "A carbon–oxygen single bond",
    158: "A carbon–nitrogen single bond",
    159: "More than one oxygen atom",
    160: "A methyl group (–CH3)",
    161: "Contains nitrogen",
    162: "Contains an aromatic ring",
    163: "Contains a 6-membered ring",
    164: "Contains oxygen",
    165: "Contains a ring",
    166: "Molecule made of more than one fragment (e.g. a salt)",
}

path = Path(__file__).parent / "maccs_keys.json"
keys = json.loads(path.read_text())
missing = [b for b in range(1, 167) if b not in HELP]
if missing:
    raise SystemExit(f"missing help for bits: {missing}")
for bit in range(1, 167):
    keys[str(bit)]["help"] = HELP[bit]
path.write_text(json.dumps(keys))
print(f"patched {len(HELP)} help strings into maccs_keys.json")
